import { prisma } from "../src/lib/prisma";

async function main() {
  const counts = {
    participants: await prisma.participant.count(),
    teams: await prisma.team.count(),
    teamMembers: await prisma.teamMember.count(),
    documents: await prisma.document.count(),
    qrPasses: await prisma.qrPass.count(),
    hostels: await prisma.hostel.count(),
    floors: await prisma.floor.count(),
    rooms: await prisma.room.count(),
    beds: await prisma.bed.count(),
    accommodationAllocations: await prisma.accommodationAllocation.count(),
    transportRoutes: await prisma.transportRoute.count(),
    transportStops: await prisma.transportStop.count(),
    transportVehicles: await prisma.transportVehicle.count(),
    transportDrivers: await prisma.transportDriver.count(),
    transportTrips: await prisma.transportTrip.count(),
    transportPassengers: await prisma.transportPassenger.count(),
    paymentTransactions: await prisma.paymentTransaction.count(),
    feeLedgers: await prisma.feeLedger.count(),
    foodPackages: await prisma.foodPackage.count(),
    foodPackageAssignments: await prisma.foodPackageAssignment.count(),
    foodConsumptions: await prisma.foodConsumption.count(),
    matches: await prisma.match.count(),
    matchEvents: await prisma.matchEvent.count(),
    courtReadinessChecks: await prisma.courtReadinessCheck.count(),
    preMatchReportings: await prisma.preMatchReporting.count(),
    resultCommunications: await prisma.resultCommunication.count(),
    courts: await prisma.court.count(),
    tournamentDays: await prisma.tournamentDay.count(),
    fixtureConfigs: await prisma.fixtureConfig.count(),
    fixturePositions: await prisma.fixturePosition.count(),
    bracketSlotAssignments: await prisma.bracketSlotAssignment.count(),
    drawHistory: await prisma.drawHistory.count(),
    spocTeamAssignments: await prisma.spocTeamAssignment.count(),
    volunteerAssignments: await prisma.volunteerAssignment.count(),
    volunteerTasks: await prisma.volunteerTask.count(),
    volunteerShifts: await prisma.volunteerShift.count(),
    volunteerIssues: await prisma.volunteerIssue.count(),
    supportTickets: await prisma.supportTicket.count(),
    supportMessages: await prisma.supportMessage.count(),
    supportEscalations: await prisma.supportEscalation.count(),
    supportAttachments: await prisma.supportAttachment.count(),
    supportKnowledgeArticles: await prisma.supportKnowledgeArticle.count(),
    announcements: await prisma.announcement.count(),
    notificationDeliveries: await prisma.notificationDelivery.count(),
    auditLogs: await prisma.auditLog.count(),
    users: await prisma.user.count(),
    officials: await prisma.official.count(),
    roles: await prisma.role.count(),
    permissions: await prisma.permission.count(),
    userRoles: await prisma.userRole.count(),
    institutions: await prisma.institution.count(),
    institutionImports: await prisma.institutionImport.count(),
    tournamentCategories: await prisma.tournamentCategory.count(),
    tournamentEvents: await prisma.tournamentEvent.count(),
    tournamentRounds: await prisma.tournamentRound.count(),
    tournamentMilestones: await prisma.tournamentMilestone.count(),
  };

  console.log("Current DB Counts:\n", JSON.stringify(counts, null, 2));
}

main().catch(console.error).finally(() => prisma.$disconnect());
